### ISSUE TITLE
[neon packaging]: make packages NOT depend on noto-sans-hinted

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#11]
please make other packages "recommend" package noto-sans-hinted, so it can be uninstalled if the system uses another font. Right now, if one wants to uninstall the package, quite many kde apps and other packages will be ripped out with it:
![screenshot_20160808_231556](https://cloud.githubusercontent.com/assets/840070/17496556/26412b14-5dbe-11e6-96b2-37be127c4137.png)

**Comment by jriddell** [comment]
updated plasma-integration with recommends and added depends to neon-seeds
