### ISSUE TITLE
[neon]: "additional drivers" (kubuntu-driver-manager) seems to do nothing when started

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#13]

**Comment by jriddell** [comment]
https://forum.kde.org/viewtopic.php?f=66&t=132729
<leszek> Riddell: aptdaemon python module is missing and conflicts with something gir-packagekit or so thats what I have in my mind still. (Tested 2 weeks ago)
<leszek> python-aptdaemon : Depends: gir1.2-packagekitglib-1.0 (< 0.9) but 1.1.0-2+16.04+build3 is to be installed

**Comment by star-buck** [comment]
seems a lot of things depend on aptdaemon, also testing gnome software center with flatpaks, etc. becomes impossible on maui/netrunner/neon...
@jriddell : We need to fix this, I came across the same dependency chain independent of that kcm 2x today while testing.

**Comment by jriddell** [comment]
Turns out this is a bug in apt-xapian-index from Ubuntu.  Fix uploaded and it's in Ubuntu's xenial-proposed available for testing, I'll publish it in a week after the testing period

https://bugs.launchpad.net/ubuntu/+source/apt-xapian-index/+bug/1579834

**Comment by star-buck** [comment]
@jriddell : is this one ready for QA?

**Comment by llelectronics** [comment]
Tested today by installing kubuntu-driver-manager on maui 1 (with latest updates) and that seems to work. It shows active proprietary drivers and allows for installing which works also (tested with microcode package installing)
So should be ready for QA.
