### ISSUE TITLE
[calamares]: locales (like language, region and timezone/format) not set correctly or fully

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#16]
neon via ubiquity sets this, so even the format of 24:00 in clock panel is right after reboot:
![screenshot_20160724_210234](https://cloud.githubusercontent.com/assets/840070/17085828/4679d1e8-51e2-11e6-854b-4a8b8547ac63.png)

**Comment by star-buck** [comment]
Teos response:


The way I see it, there are two separate issues in this report, please correct me if I got it wrong:
1) the Calamares locale setting defaults to the chosen language rather than to the chosen timezone, and
2) Calamares only sets the LANG variable and not the other ones.

I've already pushed a fix for issue (2), but not for issue (1), which is more complex.

I had initially chosen to have the locale default to the UI language because since we do not do any geolocation, this is the only locale data we can work with. I've investigated the option of having the locale setting default to the chosen timezone, but this presents some obstacles.
a) While every translated language can be associated with a locale, this is not necessarily true for timezones. The only relevant data we can get from a timezone is a country code associated with it (this can be read from zone.tab, if the distro ships this file). Then, from this country code it should be possible to get a country - not necessarily the most reliable source, but so far so good.
b) Even if we have a country, not every country is associated with a single locale, with the risk of confusing (or even offending) the user. For instance, what happens if the user's timezone choice puts him or her in Switzerland? Should we default to de_CH, fr_CH or it_CH? Another example is Belgium: whether we pre-select French or Flemish, we're offering a bad default for half the population.

Geolocation might help with this, because even with coarse IP-based geolocation we'd probably get a finer grained location than just a timezone code. However, I wouldn't go into geolocation without also porting the map widget to Marble (which is something that needs to be done anyway, with or without geolocation, as soon as possible because the current widget looks very tiny on high-DPI displays).

I can also take a deeper look at what Ubiquity is doing, just in case they have some guesswork and special-casing we can reuse, or maybe some other way to solve situations like Switzerland and Belgium, but I'm not certain that for most users the end result would be better than defaulting to the UI language as we do now.

**Comment by teo** [comment]
Update - I'm still finishing this up, but Calamares will now mimic Ubiquity's behavior as far as locale variables are concerned.

**Comment by star-buck** [comment]
using latest installer i get locales set like this, which looks good:
![locale](https://cloud.githubusercontent.com/assets/840070/17962152/cb044f20-6aaf-11e6-80de-ac90ae5ba7d5.png)
still the clock is not set correctly, whereas with ubuiquity/neon, it does apply the +2 hours timezone... any idea what neon/ubiquity does to get the clock automatically set right?

**Comment by teo** [comment]
@star-buck no idea yet, but I'm looking into it. Is the clock only wrong in Plasma, or does the `date` command also yield the wrong time?

**Comment by star-buck** [comment]
odd thing is:
on arm odroid it gets set correctly, only on the pc ubiquity sets it right, while calamares somehow doesnt.

**Comment by teo** [comment]
@star-buck ok, I tested some things and now I know what's up. Your information about the ODROID was crucial: Calamares on ODROID runs in no-chroot mode, so it sets the timezone with timedatectl (systemd), whereas in installer mode we can't do that. Currently working on a fix.
