### ISSUE TITLE
[neon]: on neon/maui ubiquity doesnt show option "install alongside" anymore

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#19]
same machine trying to use previous kubuntu based netrunner vs. original neon user edition, where it would have been perfectly fine to install alongside:
![ubiquity](https://cloud.githubusercontent.com/assets/840070/17644962/767b90ba-6197-11e6-86b1-5f4f7f9d88af.png)

missing on neon/maui:
![ubiquity screenshot_20160813_181207](https://cloud.githubusercontent.com/assets/840070/17644963/7b1b08f8-6197-11e6-9977-ef8a8fbb2c17.png)

Any ideas?

**Comment by star-buck** [comment]
same with just one partition:
![ubiquity screenshot_20160813_185709](https://cloud.githubusercontent.com/assets/840070/17645026/872cca8a-6199-11e6-862f-bc1a92c779ba.png)

**Comment by star-buck** [comment]
here is the log:
https://www.dropbox.com/s/kdlnf7unxw4rkta/ubiquity.debug.txt?dl=0
maybe some size isnt set properly?

**Comment by star-buck** [comment]
testing calamares for maui 2

**Comment by jriddell** [comment]
whether it offers to resize just depends on whether the installer thinks there is enough free space to be able to do so.  When there's not enough free space to be able to do so it won't offer it

**Comment by star-buck** [comment]
so in the examples above, 159GB or the 1 partition of 500GB isnt enough?

**Comment by star-buck** [comment]
the reason i closed this is because for maui and netrunner we switch to calamares, but ill test neon for that anyway whenever i download a new dev ISO in the future, no need to pursue this imo further unless its a topic for neon.
