### ISSUE TITLE
[maui-1]: switching to kickoff shows kde gear icon and throws error

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#20]
![kickoff_screenshot_20160814_201232](https://cloud.githubusercontent.com/assets/840070/17651185/ce230850-6261-11e6-9b36-4e3f7128c3b0.png)

**Comment by llelectronics** [comment]
I can't reproduce it here. Is there any backports or testing ppa activated. Did you upgrade anything ? 
Or did you maybe removed some packages ?
Maybe you changed the Look and Feel package ? (That includes the scripts for each menu to configure icon and favorites)
Tested here freshly installed maui build23i and updated 23c and both work fine.

**Comment by star-buck** [comment]
seems solved
