### ISSUE TITLE
[systray]: reported: missing some icons after update to frameworks 26

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#26]
https://forums.mauilinux.org/showthread.php?tid=23952

**Comment by star-buck** [comment]
i couldnt confirm this with latest maui 2 dev img, but maybe maui 1 still had something slightly differently configured.

**Comment by jriddell** [comment]
Looks like it's fixed, closing
https://bugs.kde.org/show_bug.cgi?id=366283
