### ISSUE TITLE
[5.7.2]: desktop themes kcm: downloading new desktop themes dont show in list until closing complete ss and reopen kcm

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#3]
this looks like nothing downloaded at all, therefore is confusing

**Comment by notmart** [comment]
i can reproduce it on a devel setup, i think i know what is going on and should be easily fixable

**Comment by notmart** [comment]
should be fixed in master and 5.7, so for next point release

**Comment by notmart** [comment]
should be fixed in 5.7.3

**Comment by star-buck** [comment]
works
