### ISSUE TITLE
[5.7.2]: ghns: desktop themes kcm: installed themes not listed as "installed"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.7#4]
![ghns_20160724_164714](https://cloud.githubusercontent.com/assets/840070/17084442/18d0182a-51be-11e6-9883-29d7f70e1a1d.png)

**Comment by notmart** [comment]
on local machine seems to correctly mark them as installed, will try on different setups to see what may cause different results

**Comment by notmart** [comment]
managed to reproduce, found the issue, so fix is now in 5.7 and master

**Comment by notmart** [comment]
should be fixed in 5.7.3

**Comment by star-buck** [comment]
works
